# Generated by Django 4.1.4 on 2023-04-07 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_brand_image_alter_product_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_customer"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopcart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_shopcart",
                to="products.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="shopcart",
            name="product_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_color_shopcart",
                to="products.productcolor",
                verbose_name="رنگ",
            ),
        ),
        migrations.AlterField(
            model_name="shopcart",
            name="qty",
            field=models.IntegerField(default=0, verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="shopcart",
            name="total_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="قیمت کل"
            ),
        ),
        migrations.AlterField(
            model_name="shopcart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_shopcart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ درج"
                    ),
                ),
                (
                    "update_date",
                    models.DateField(auto_now=True, verbose_name="تاریخ آخرین ویرایش"),
                ),
                (
                    "is_finaly",
                    models.BooleanField(default=False, verbose_name="نهایی شده"),
                ),
                (
                    "order_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="کد سفارش",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="مقدار تخفیف سفارش",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
            },
        ),
        migrations.AddField(
            model_name="shopcart",
            name="order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_details",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
    ]
