# Generated by Django 4.1.4 on 2023-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_shopcart_product_alter_shopcart_product_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="مقدار تخفیف سفارش"
            ),
        ),
    ]
