# Generated by Django 4.1.4 on 2023-04-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopcart",
            name="order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_details",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
    ]
