# Generated by Django 4.1.4 on 2023-04-16 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_shopcart_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_title",
                    models.CharField(max_length=50, verbose_name="عنوان پرداخت"),
                ),
            ],
            options={
                "verbose_name": "نوع روش پرداخت",
                "verbose_name_plural": "انواع روش پرداخت",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_types",
                to="orders.paymenttype",
                verbose_name="روش پرداخت",
            ),
        ),
    ]
