# Generated by Django 4.1.4 on 2023-06-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_paymenttype_order_description_order_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان")),
            ],
            options={
                "verbose_name": "وضعیت سفارش",
                "verbose_name_plural": "وضعیت های سفارش",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_state",
                to="orders.orderstate",
                verbose_name="وضعیت سفارش",
            ),
        ),
    ]
