# Generated by Django 4.1.4 on 2023-06-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderstate_order_order_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopcart",
            options={"verbose_name": "سبد خرید", "verbose_name_plural": "سبد خرید ها"},
        ),
    ]
