# Generated by Django 4.1.4 on 2023-04-22 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0005_paymenttype_order_description_order_payment_type"),
        ("accounts", "0010_alter_customer_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین ویرایش پرداخت"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="مبلغ پرداخت")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات پرداخت"
                    ),
                ),
                (
                    "is_finally",
                    models.BooleanField(default=False, verbose_name="وضعیت پرداخت"),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="کد وضعیت درگاه پرداخت"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شماره پیگیری",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_customer",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_order",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت ها",
            },
        ),
    ]
