# Generated by Django 4.1.4 on 2023-02-24 20:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summery_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="توضیحات کوتاه کالا"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="توضیحات برند"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر برند"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="توضیحات کالا"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_features",
                to="products.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_gallery",
                to="products.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="توضیحات گروه"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر گروه"
            ),
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="نام رنگ")),
                ("color", models.CharField(max_length=10, verbose_name="رنگ")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_colors",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ ها",
            },
        ),
    ]
