# Generated by Django 4.1.4 on 2023-02-26 17:53

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_product_summery_description_alter_brand_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="value_added",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="ارزش افزوده"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر برند"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="رنگ",
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر گروه"
            ),
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_title",
                    models.CharField(max_length=100, verbose_name="عنوان مقدار"),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.feature",
                        verbose_name="ویژگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ویژگی",
                "verbose_name_plural": "مقادیر ویژگی",
            },
        ),
        migrations.AddField(
            model_name="productfeature",
            name="filter_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.featurevalue",
                verbose_name="کلید مقدار",
            ),
        ),
    ]
