# Generated by Django 4.1.4 on 2023-04-01 10:34

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productcolor_value_added_alter_brand_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر برند"
            ),
        ),
        migrations.AlterField(
            model_name="featurevalue",
            name="feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_values",
                to="products.feature",
                verbose_name="ویژگی",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر گروه"
            ),
        ),
    ]
