# Generated by Django 4.1.4 on 2023-05-23 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_brand_image_alter_product_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment_scoring_favorites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "scor",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_scoring",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "scoring_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scoring",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر امتیاز دهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز",
                "verbose_name_plural": "امتیازات",
            },
        ),
    ]
