# Generated by Django 4.1.4 on 2023-05-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment_scoring_favorites", "0002_scoring"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scoring",
            old_name="scor",
            new_name="score",
        ),
    ]
