# Generated by Django 4.1.4 on 2023-05-24 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_brand_image_alter_product_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment_scoring_favorites", "0003_rename_scor_scoring_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "favorite_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_favorite",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر امتیاز دهنده",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_favorite",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه",
                "verbose_name_plural": "علایق",
            },
        ),
    ]
