# Generated by Django 4.1.4 on 2023-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobail_number",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="شماره موبایل"
            ),
        ),
    ]
