# Generated by Django 4.1.4 on 2023-02-24 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربر ها"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="active_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="کد فعال سازی"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=200, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="family",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="نام خانوادگی"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("True", "مرد"), ("False", "زن")],
                default="True",
                max_length=50,
                null=True,
                verbose_name="جنسیت",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="فعال / غیر فعال"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="ادمین / غیر ادمین"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="register_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ درج"
            ),
        ),
    ]
