# Generated by Django 4.1.4 on 2023-04-13 19:34

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "مشتری", "verbose_name_plural": "مشتری ها"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.FileUpload.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
