# Generated by Django 4.1.4 on 2023-04-13 19:35

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customer_options_alter_customer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.FileUpload.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
