# Generated by Django 4.1.4 on 2023-04-16 06:10

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره موبایل"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.FileUpload.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
