# Generated by Django 4.1.4 on 2023-05-24 07:33

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_customer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                default="images/default.png",
                upload_to=utils.FileUpload.upload_to,
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
