# Generated by Django 4.1.4 on 2023-06-28 09:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="متن اسلایدر"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=utils.FileUpload.upload_to,
                        verbose_name="تصویر اسلایدر",
                    ),
                ),
                (
                    "slider_link",
                    models.URLField(
                        blank=True, max_length=300, null=True, verbose_name="لینک"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="فعال / غیر فعال"
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلایدها",
            },
        ),
    ]
