# Generated by Django 4.1.4 on 2023-05-10 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0013_alter_brand_image_alter_product_image_and_more"),
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "انبار", "verbose_name_plural": "انبارها"},
        ),
        migrations.AlterModelOptions(
            name="warehousetype",
            options={"verbose_name": "نوع انبار", "verbose_name_plural": "انواع انبار"},
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="قیمت تراکنش"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse_products",
                to="products.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="qty",
            field=models.IntegerField(verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="register_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="user_registered",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse_user_registered",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر ثبت کننده",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouses",
                to="warehouses.warehousetype",
                verbose_name="نوع انبار",
            ),
        ),
        migrations.AlterField(
            model_name="warehousetype",
            name="title",
            field=models.CharField(max_length=50, verbose_name="نوع انبار"),
        ),
    ]
